apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-toleration-rs
  labels:
    app: nginx-toleration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-toleration
  template:
    metadata:
      labels:
        app: nginx-toleration
    spec:
      tolerations:
      - key: "app"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"
      containers:
      - image: nginx
        name: nginx
