apiVersion: apps/v1
kind: Deployment
metadata:
  name: neginx-dep
  labels:
    app: nginx-app
    type: nginx-front
spec:
  template:
    metadata:
      labels:
        run: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
  replicas: 2
  selector:
    matchLabels:
      run: nginx
