apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  name: my-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      containers:
      - image: nginx
        name: nginx
