apiVersion: v1
kind: LimitRange
metadata:
  name: priority-limit
  namespace: priority-app
spec:
  limits:
  - max:
      cpu: "2"
      memory: "1Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "500m"
      memory: "256Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    type: Container
  - max:
      cpu: "4"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Pod
