apiVersion: v1
kind: ResourceQuota
metadata:
  name: priority-quota
  namespace: priority-app
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
    pods: "20"
    services: "10"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values: [ "high-priority", "medium-priority", "low-priority" ]
